language: android
jdk: oraclejdk7
android:
  components:
    - platform-tools
    - tools
    - android-19
    - build-tools-22.0.1
    - extra-google-m2repository
    - extra-android-m2repository
sudo: false
script:
  - cd SSIDLogger
  - ./gradlew assemble --stacktrace
  - ../travis.sh
env:
  matrix:
    - ANDROID_TARGET=android-19
  global:
    secure: "o7IuyARl9WoVJGeQMAohw47aP9kiZnn5kdjaRIdR/b3nllySB8ugfLrdZpP41v3+TDGz03pEWALYAunFVEQvycvAjp2hQWkwu/Mbk51ptAgowEG+9KbrtldeK4471TtlhNRwZ7m9qkBk1kdG7qO7991MCIP7B51Bo/5QqSll5X0="
